---
- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: False

- name: Register runner to GitLab (non-docker executors)
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner_description }}'
    --tag-list '{{ gitlab_runner_tags | join(",") }}'
    --executor '{{ gitlab_runner_executor }}'
    --request-concurrency {{ gitlab_runner_concurrent }}
  when: gitlab_runner_executor != 'docker' and configured_runners.stderr.find('{{ gitlab_runner_description }}') == -1

- name: Create /home/gitlab-runner
  file:
    path: /home/gitlab-runner
    state: directory
    owner: gitlab-runner
    group: gitlab-runner
  when: gitlab_runner_executor == 'docker'

- name: Register runner to GitLab (docker executor)
  command: gitlab-runner register >
    --non-interactive
    --url '{{ gitlab_runner_coordinator_url }}'
    --registration-token '{{ gitlab_runner_registration_token }}'
    --description '{{ gitlab_runner_description }}'
    --tag-list '{{ gitlab_runner_tags | join(",") }}'
    --executor '{{ gitlab_runner_executor }}'
    --request-concurrency {{ gitlab_runner_concurrent }}
    --docker-image '{{ gitlab_runner_docker_image }}'
    --docker-privileged
    --cache-dir "{{ gitlab_runner_docker_cache }}"
  when: gitlab_runner_executor == 'docker' and configured_runners.stderr.find('{{ gitlab_runner_description }}') == -1
